apiVersion: hanapedia.link/v1alpha1
kind: NATConfig
metadata:
  name: domestic1
spec:
  externalIPPool:
    - 10.70.0.1/32
  portRangeSize: 100
  targetCIDRs:
    - 192.168.10.0/24
    - 192.168.0.0/24
  podSelector:
    matchLabels:
      app: domestic1-client
  nodeSelector:
    matchLabels:
      mooring.hanapeida.link/advertise: "true"
